name: sharevoices
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: 2.4.1
  flutter_riverpod: 2.6.1
  shared_preferences: 2.5.3
  file_picker: 10.0.0
  device_info_plus: 11.3.0
  permission_handler: 11.4.0
  toastification: 2.3.0
  audioplayers: ^6.4.0
  share_plus: ^10.1.4
  avatar_plus: 0.0.5
  flutter_svg: 2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf